#!/usr/bin/env bash

help() {
    echo "Retrieve the value of the secret"
    echo "-n name of the secret"
    echo "-p true to get the whole payload"
    exit 1
}

while getopts ":n:p:" arg; do
    case $arg in
        n) NAME=$OPTARG;;
        p) PAYLOAD=true;;
        *) help ;;
    esac
done

[ -z "$NAME" ] && help

val=$(aws secretsmanager get-secret-value --secret-id $NAME)

if [ $PAYLOAD ]; then
    echo $val
else
    echo $val | jq '.SecretString' | tr -d '"' | sed 's/\\n/\n/g'
fi
