# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"create": "userpass.ipynb",
         "update": "userpass.ipynb",
         "get": "userpass.ipynb",
         "delete": "userpass.ipynb",
         "CLIENT": "secret.ipynb",
         "run_localstack": "secret.ipynb",
         "make_local_client": "secret.ipynb",
         "dump": "userpass.ipynb",
         "load": "userpass.ipynb"}

modules = ["grafanakey.py",
           "secret.py",
           "userpass.py"]

doc_url = "https://talosiot.github.io/vera/"

git_url = "https://github.com/talosiot/vera/tree/master/"

def custom_doc_links(name): return None
