# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/grafanakey.ipynb (unless otherwise specified).

__all__ = ['create', 'update', 'get', 'delete']

# Cell
import vera.secret as secret


# Cell

def _name(host, org):
    '''
    host is the grafana host.  e.g. dashboard.talosiot.com
    org is the organization number. e.g. 7
    '''
    return "grafana/{h}/org/{org}".format(h=host, org=org)

def create(host, org, key, **kwargs):
    value = key
    name = _name(host, org)
    return secret.create(name=name, value=value, **kwargs)

def update(host, org, key, **kwargs):
    value = key
    name = _name(host, org)
    return secret.update(name=name, value=value, **kwargs)

def get(host, org, **kwargs):
    name = _name(host, org)
    return secret.get(name=name, **kwargs)

def delete(host, org, **kwargs):
    name = _name(host, org)
    return secret.delete(name=name, **kwargs)
