# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/secret.ipynb (unless otherwise specified).

__all__ = ['CLIENT', 'run_localstack', 'make_local_client', 'get', 'create', 'update', 'delete']

# Cell
import boto3
CLIENT = boto3.client('secretsmanager')

# Cell
from scylla import run_container, set_port_name
import localstack_client.session

def run_localstack(version="latest", **kwargs):
    env = {'SERVICES':'secretsmanager'}
    additional_kwargs = {'environment': env}
    additional_kwargs.update(kwargs)
    ports = {4566:4566}
    image = 'localstack/localstack:{}'.format(version)
    ls_container = run_container(image, ports=ports, block_until_port_available=4566,
                                   **additional_kwargs)
    ls_container = set_port_name(ls_container, 4566, 'entry')
    return ls_container

def make_local_client():
    session = localstack_client.session.Session()
    return session.client('secretsmanager')

# Cell
def get(name, client=None, **kwargs):
    '''
    Retrieves the secret with the given name
    '''
    client = client or CLIENT
    resp = client.get_secret_value(SecretId=name, **kwargs)
    str_value = resp.get('SecretString')
    byte_value = resp.get('SecretBytes')
    return str_value or byte_value

def create(name, value, client=None, **kwargs):
    '''
    Create a new secret with Name=name
    If you want SecretBytes instead of SecretString
    set value=None and specify SecretBytes in kwargs
    '''
    client = client or CLIENT
    if value is not None:
        kwargs['SecretString'] = value

    resp = client.create_secret(Name=name, **kwargs)
    ok = resp['ResponseMetadata']['HTTPStatusCode']==200
    return ok, resp

def update(name, value, client=None, **kwargs):
    '''
    Update the value of a secret with SecretId=name
    '''
    client = client or CLIENT
    if value is not None:
        kwargs['SecretString'] = value

    resp = client.put_secret_value(SecretId=name, **kwargs)
    ok = resp['ResponseMetadata']['HTTPStatusCode']==200
    return ok, resp

def delete(name, client=None, **kwargs):
    '''
    Schedule the secret with SecretId=name for deletion
    '''
    client = client or CLIENT
    resp = client.delete_secret(SecretId=name, **kwargs)
    ok = resp['ResponseMetadata']['HTTPStatusCode']==200
    return ok, resp