# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/userpass.ipynb (unless otherwise specified).

__all__ = ['dump', 'load', 'create', 'get', 'update', 'delete']

# Cell
import json
import vera.secret as secret


# Cell

def dump(user, password):
    assert user is not None
    assert password is not None
    return json.dumps([user, password])

def load(userpass):
    return json.loads(userpass)

def _name(program, host, role=None, user=None):
    if role:
        suffix="role={}".format(role)
    else:
        suffix="user={}".format(user)
    return "{p}/{h}/userpass/{s}".format(p=program, h=host, s=suffix)

def create(program, host, role=None, user=None, password=None, **kwargs):
    value = dump(user, password)
    name = _name(program=program, host=host, role=role, user=user)
    return secret.create(name=name, value=value, **kwargs)

def get(program, host, role=None, user=None, **kwargs):
    name = _name(program=program, host=host, role=role, user=user)
    return load(secret.get(name=name, **kwargs))

def update(program, host, role=None, user=None, password=None, **kwargs):
    value = dump(user, password)
    name = _name(program=program, host=host, role=role, user=user)
    return secret.update(name=name, value=value, **kwargs)

def delete(program, host, role=None, user=None, **kwargs):
    name = _name(program=program, host=host, role=role, user=user)
    return secret.delete(name=name, **kwargs)
