name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        AWS_DEFAULT_REGION: us-west-1  #west so as to not accidentially write secrets to east where it matters
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: nbdevCI
      uses: talosiot-will/nbdevCI@v1
      with: 
        nbdev_test_nbs_args: "--n_workers=1"
