name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        AWS_DEFAULT_REGION: us-west-1  #west so as to not accidentially write secrets to east where it matters
        NBDEV_TEST_NBS_ARGS: "--n_workers 1"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Clone nbdevCI
      run: git clone https://github.com/talosiot-will/nbdevCI.git nbdevCI
    - name: Install requirements
      run: nbdevCI/install_requirements
    - name: Run nbdevCI
      run: nbdevCI/entrypoint.sh
    - name: Remove nbdevCI
      run: rm -rf nbdevCI
